### ISSUE TITLE
hoprd API requirements / design

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/myne-chat#10]
hoprd support a websocket and HTTP based API which is command oriented and responds with plain text. The chat app might need a more structured API which also provides typed responses (JSON).

**Comment by nionis** [comment]
a few thoughts:

As we will be using `HOPRd` to provide the API for myne-chat, I think it makes sense to:

- use websocket interface to `read` incoming messages
- extend `HOPRd's` rest API with the available commands
  > ideally we would find a way to hook up all available commands to the rest API without any duplication
  
alternatively, we would need to rely on reading incoming text from the websocket to figure out the "response" - which is very hacky and hard to work with, especially for external devs

**Comment by tolbrino** [comment]
An interesting approach to API documentation.

First create the spec using [Swagger](https://swagger.io/tools/swagger-ui/). Then use [ReDoc](https://github.com/redocly/redoc) to turn the spec into a nice website which can be incorporated into other websites more easily than the original Swagger template.

Example output:

https://docs.docker.com/
https://docs.discourse.org/

**Comment by tolbrino** [comment]
I've settled to use Swagger, spec will be added to the repo shortly. Then the implementation follows.
