### ISSUE TITLE
Add code conventions via linting/prettier tooling

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/myne-chat#110]
### Is your feature related to a problem?

Currently there are no code conventions on the project.

### Describe the feature you'd like

Ideally we use something like `js-standard` and enforce via `prettier` and `githooks` to run linters on commit/push.

### Describe alternatives you've considered

Auto-commits as we do in `hoprnet`, but CI feels like the wrong place to deal with this (wasting CI cycles on code that wasn't verified in the workstation).

### Additional context

This is relevant for our contribution guidelines.

**Comment by mjadach-iv** [comment]
Closing issue as the myne-chat project is closed for the time being. 
Will need to reopen if we will be updating the repo.
