### ISSUE TITLE
UI: detail corrections

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/myne-chat#119]
- please colour the scroll-bar instead of FFFFFF in C3C3C3:
![Bildschirmfoto 2022-02-07 um 17 18 19](https://user-images.githubusercontent.com/78225531/152831531-746b88a4-c26c-489b-b36d-e52d901c2bab.png)

- please shrink the icon-set so that it‘s still visible on a Tablet-device in portrait format. Please also consider the hover square around every element into the consideration:
![Bildschirmfoto 2022-02-07 um 17 24 29](https://user-images.githubusercontent.com/78225531/152829044-55ae8a77-c548-46a6-bdec-7ad64ffb3a52.png)

**Comment by jjperezaguinaga** [comment]
Fixed in [96597ba](https://github.com/hoprnet/myne-chat/commit/96597ba0496eea1e5f0e9eb5c800011aedb6e11b)
