### ISSUE TITLE
Deploy our `mocks` server to Vercel using the `pages/api` directory to allow exposure via its API

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/myne-chat#127]

**Comment by jjperezaguinaga** [comment]
It should be noted that Vercel does not support WebSockets so we need to deploy this somewhere else, ideally in an existing provider like Cloudflare.

**Comment by mjadach-iv** [comment]
Closing issue as the myne-chat project is closed for the time being. 
Will need to reopen if we will be updating the repo.
