### ISSUE TITLE
MyneChat getting started guide

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/myne-chat#4]
# Background

To start working with MyneChat locally, you need to either run an interconnected network or use our `mocks` server. The last process is documented in the README, but the first one isn't.

Also, if you go to https://app.myne.chat/, it's not immediately obvious what to do or how to get started. The application on its own can't actually do anything without a HOPRd node, which needs to be connected as part of a network of funded nodes. This setup is a bit cumbersome and ever worse, undocumented.

# Introduction

Provide instructions on how to run an interconnected HOPR network and how to start MyneChat and connect to it. Improve the README to point out these steps and use the "quick settings" URL command. Finally, when starting MyneChat, we should provide a series of messages to the users (see #61), which showcase to the user what to do and how to get started.

# Tasks

- [x] https://github.com/hoprnet/hoprnet/issues/3329
- [x] #103
- [x] #108

**Comment by jjperezaguinaga** [comment]
Moved to `0.2`, updating milestone.

**Comment by jjperezaguinaga** [comment]
Replacing https://github.com/hoprnet/myne-chat/issues/61 for https://github.com/hoprnet/myne-chat/issues/108 to isolate the UX improvements pointed out by @ReinhardSchmidt but outside of `0.2`
