### ISSUE TITLE
when receiving msg, should scroll down automatically

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/myne-chat#42]
when there's more msgs than fit on one screen, the user has to scroll down manually to see the latest msg. would be cool to scroll automatically to not miss msgs.

**Comment by nionis** [comment]
seems to not work when window is resized

**Comment by mjadach-iv** [comment]
Closing issue as the myne-chat project is closed for the time being. 
Will need to reopen if we will be updating the repo.
