### ISSUE TITLE
Confirm if node is sending 0 or 1 or 2 or 3 hop msgs

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/myne-chat#43]
we can send msgs from my Laptop to cloud and back. It works for both nodes not having any channels open. That is somewhat unexpected and not according to specs (minimally 2 hops). I then opened a channel from cloud node to some other cloud node. Sending msgs in both directions still works. I expect that the cloud node sens at least a 1 hop msg but I have no way to confirm that. Any ideas? I guess that's possible via some low level logs on the recipient machine that shows the last relayer who is != the sender?

**Comment by jjperezaguinaga** [comment]
Right now `hoprd` is the one responsible of taking care of this, i.e. the `path` is derived in `hopr-core` as shown here:

https://github.com/hoprnet/hoprnet/blob/d1adb86c13e5370125b21b7284ec6fe58d7e1bb3/packages/hoprd/src/api/v2/paths/messages.ts#L14-L20

There was a version I believe that had `path` hardcoded which would have effectively made `0` hops to work, but I couldn't find the commit. @tolbrino and @nionis can confirm or deny this.

For now, the default setting is `2` hops in `hopr-core` and that's the amount of nodes needed for a message to successfully arrive.

**Comment by nionis** [comment]
This should be fixed right now. Fixed in https://github.com/hoprnet/hoprnet/pull/3175

**Comment by jjperezaguinaga** [comment]
Perfect, closing then, thanks for chimming in @nionis
