### ISSUE TITLE
Message is shown as sent even though no path was found

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/myne-chat#47]
Myne Chat uses automatic path finding in the hoprd node. Thus, an error case is that no path is found and a `422` HTTP response error is returned. In such cases, the UI should show that the message could not be sent so that the user can open channels as needed.

Response Body:

```
{"error":"Path not found"}
```

Response Error Code:

```
HTTP/1.1 422 Unprocessable Entity
```

**Comment by jjperezaguinaga** [comment]
@tolbrino moving forward it would be awesome to have an expected behaviour, current behaviour, steps to reproduce, etc.

**Comment by jjperezaguinaga** [comment]
New issues discovered during the development of this one:

- #49
- hoprnet/hoprnet#3181
