### ISSUE TITLE
MyneChat UX/UI improvements (v0.4)

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/myne-chat#61]
# Background

As discussed with @ReinhardSchmidt, we need to do a few minor UX/UI improvements for allowing MyneChat to be properly used as a demo showcase of the HOPR network.

# Task Description
- **Welcome messages** Add a stream of messages that can be replied with to showcase users with the minimal set of instructions to follow to learn how to use MyneChat.

e.g.
```
Message 1: "Welcome to myne! Finally chat privately."
Message 2: "For initiating a chat conversation, please run HOPRnode (if you don‘t know how to - visit XXX), then click in the left side-bar on "Add conversation". If you got further questions, visit: myne.chat/faq."
```

- **HOPRd-less bots** Create a series of bots that users can interact with that are not necessarily behind a HOPR node but are able to showcase some minor functionality for the chat. These should also populate our UI to allow providing feedback via usepastel.com easier.

# Tasks

**Welcome messages**
- [x] #108

**HOPRd-less bots**
_Removed from this epic to favor #102_

- ~#126~
- ~#127~
- ~#128~
- ~#129~
- ~#131~

## Tasks
- [ ] #42 
- [ ] #53
- [x] #132
- [x] #110
- [x] #130

**Comment by robertkiel** [comment]
@jjperezaguinaga please update

**Comment by jjperezaguinaga** [comment]
Divided this task into two epics: #102 which can be quickly solved and this one, which is probably not a priority, but retains the pending yet important feedback from both @ReinhardSchmidt and myself on UX, as well as all the other ones given by the rest of the team across the app development (e.g. @nionis and @SCBuergel).

**Comment by mjadach-iv** [comment]
Closing issue as the myne-chat project is closed for the time being. 
Will need to reopen if we will be updating the repo.
