### ISSUE TITLE
specification for app development approach

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/myne-chat#7]

**Comment by nionis** [comment]
Some thoughts from my time playing around / thinking about it:

I think we should go with next.js to build this project, it makes it very easy for us to get started & eventually host it if needed.

- create a "basic" NextJS powered webapp
- coding: typescript
- state management: immer
- layouting: flexbox
- styling/components: rebass
- routing: next.js
- bundling: next.js

Does myne-chat need to be a SPA? honestly am not sure - by looking at the design and what it aims to achieve, at the moment, it's just a single page - and by using vanilla next.js we can achieve what we need. The value of SPAs is that you never have to reload the website, in this webapp, we only have one page.
The question becomes whether the value of implementing `react-router` or setup `nextjs/router` to work as a SPA is really worth it. I would be totally fine with skipping this part altogether until it becomes a necessity.

**Comment by nionis** [comment]
After experimentation, found out that rebass is not a good option as it's no longer being maintained.

- create a "basic" NextJS powered webapp
- coding: typescript
- state management: immer
- layouting/components: grommet
- styling: styled-components (also used by grommet internally)
- routing: next.js
- bundling: next.js
